# tinyinstaller distros.conf
# Format: Name|URL
Debian 13 Trixie Netinstall|https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.4.0-amd64-netinst.iso
Debian 12 Bookworm Netinstall|https://cdimage.debian.org/cdimage/archive/12.13.0/amd64/iso-cd/debian-12.13.0-amd64-netinst.iso
Arch Linux|https://mirror.rackspace.com/archlinux/iso/latest/archlinux-x86_64.iso
CachyOS Desktop|https://cdn77.cachyos.org/ISO/desktop/260308/cachyos-desktop-linux-260308.iso
Linux Mint 22.3 Cinnamon|https://pub.linuxmint.io/stable/22.3/linuxmint-22.3-cinnamon-64bit.iso
Pop!_OS 24.04|https://iso.pop-os.org/24.04/amd64/generic/23/pop-os_24.04_amd64_generic_23.iso
Ubuntu 24.04 Desktop|https://releases.ubuntu.com/noble/ubuntu-24.04.4-desktop-amd64.iso
Ubuntu 24.04 LTS Server|https://releases.ubuntu.com/noble/ubuntu-24.04.4-live-server-amd64.iso
Fedora 43 Workstation|https://download.fedoraproject.org/pub/fedora/linux/releases/43/Workstation/x86_64/iso/Fedora-Workstation-Live-43-1.6.x86_64.iso
NixOS 25.11 Minimal|https://channels.nixos.org/nixos-25.11/latest-nixos-minimal-x86_64-linux.iso
FreeBSD 15.0|https://download.freebsd.org/releases/amd64/amd64/ISO-IMAGES/15.0/FreeBSD-15.0-RELEASE-amd64-disc1.iso
NetBSD 10.1|https://cdn.netbsd.org/pub/NetBSD/NetBSD-10.1/images/NetBSD-10.1-amd64.iso
openSUSE Tumbleweed|https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-DVD-x86_64-Current.iso
Alpine Linux 3.23.3|https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/x86_64/alpine-standard-3.23.3-x86_64.iso
Void Linux|https://repo-default.voidlinux.org/live/current/void-live-x86_64-20250202-base.iso
Gentoo Minimal|https://gentoo.osuosl.org/releases/amd64/autobuilds/current-install-amd64-minimal/install-amd64-minimal-20260329T161601Z.iso
Gentoo LiveGUI|https://gentoo.osuosl.org/releases/amd64/autobuilds/current-livegui-amd64/livegui-amd64-20260215T164556Z.iso
Kali Linux 2025.4|https://cdimage.kali.org/kali-2025.4/kali-linux-2025.4-installer-amd64.iso
System Rescue|https://fastly-cdn.system-rescue.org/releases/13.00/systemrescue-13.00-amd64.iso
